### ISSUE TITLE
update-aurto can conflict with a running `aurto add`

### ISSUE THREAD

**Issue by ScoreUnder** [alexheretic/aurto#16]
While running `aurto add` on a package, `update-aurto` can kick in and end up removing the PKGBUILD (and presumably other things) part-way through, causing the command to fail.

**Comment by alexheretic** [comment]
Thanks I'll test this, I did think the chroot locking would be enough but it doesn't sound like that's true. It should be fairly easy to ensure update-aurto & `aurto add` don't overlap.

**Comment by alexheretic** [comment]
Hey I'm having trouble reproducing this. When I test, for example, 3 concurrent `aurto add dpkg` equivalent to calling `aur sync --no-view --no-confirm --chroot --database=aurto --makepkg-conf=/etc/aurto/makepkg-chroot.conf dpkg` in 3 terminals one after the other I get no issue.

Each terminal essentially waits for the previous to finish building before it starts, and this is (I would have thought) because the chroot is locked by aurutils.

Can you provide your error output and a decent way to reproduce (if possible)?

**Comment by ScoreUnder** [comment]
I don't have a consistent way to reproduce, but I believe it's something to do with the "clean aurutils cache" step at the end of the script. If update-aurto finishes with nothing interesting to do, but a long `aurto add` is in progress, I suspect that it's having the cache directory (currently in use) deleted by the update script.

**Comment by alexheretic** [comment]
Ah good point thanks, I can see how that can cause issues.

**Comment by alexheretic** [comment]
aurutils cache cleaning will be avoided when `aurto add` is running in future version, see c70683134e297f035459e57922353485a9205b0a.

I'll make a release at the end of the week.
