### ISSUE TITLE
Enable multilib repo

### ISSUE THREAD

**Issue by ScoreUnder** [alexheretic/aurto#47]
Currently aurto doesn't seem to recognise packages in the multilib repo, so fails to build all AUR packages that depend on them (e.g. openmpt→wine; air-for-steam→steam).

**Comment by alexheretic** [comment]
Presumably because aurutils default to `/usr/share/devtools/pacman-extra.conf` for chroot building and this doesn't have multilib enabled.

We could probably default aurto to use the aur sync arg `--pacman-conf=/usr/share/devtools/pacman-multilib.conf` to fix this.

There may be some cases where people don't want this, so it might be better to bring that conf into aurto and have a `/etc/aurto/pacman-chroot.conf` editable file.

**Comment by alexheretic** [comment]
This should be fixed by default in `0.10.3` & users can disable multilib in `/etc/aurto/pacman-chroot.conf` if desired.
