### ISSUE TITLE
Stuck validating source files

### ISSUE THREAD

**Issue by N-kay** [alexheretic/aurto#48]
I have not seen this mentioned anywhere yet, but no matter which aur package I try to add, aurto never advances past the validation stage. sha256sum is installed, no further output or error is given. No verbose or debug options seem to exist.

**Comment by alexheretic** [comment]
The output is reduced, is only printed in full after a failure. It could just be taking a while to setup the chroot env, the reduced output doesn't always make it very clear that stuff is happening. You can run the underlying aurutils `aur sync ...` command that aurto prints yourself for the full output.

**Comment by N-kay** [comment]
I'll admit I overlooked that entirely. Simply copy-pasting the underlying command works so far (currently compiling).

Does aurto run the command(s) as a different user? Maybe that's why it fails.

**Comment by alexheretic** [comment]
I think it's _not_ failing, it's just not showing the output because it only shows lines that start with `==>` or `  ->` which I think at one time worked well to summarize which phase you were in without the full output.

It should show the latest line, which would show progress better. Or maybe just bin the idea of summarizing the output... I'll raise an issue to improve that.

**Comment by alexheretic** [comment]
I assume this is fixed now we show more output. Let me know otherwise.
